from .title_view import *
from .version_view import *
from .categories_table_view import *
from .category_prompt_view import *
from .end_game_view import *
from .exit_game_view import *
from .hangman_view import *
from .blanks_group_view import *
from .blanks_group_view import *
from .keyboard_view import *
from .keyboard_letter_prompt import *
from .reset_game_view import *
